name: build-theme

on:
  push:
    branches:
      - "*"
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build theme.
        run: |
          composer install --no-dev

          npm install
          npm run production

      - name: "Deploy theme to SFTP and release."
        uses: docker://ghcr.io/sitepilot/wp-sftp-deploy:latest
        env:
          SP_SFTP_KEY: ${{ secrets.WP_UPDATE_SFTP_KEY }}
          SP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SP_VERSION_FILE: "style.css"
        if: github.event.release
