name: deploy

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - run: |
          composer install --no-progress --no-dev
          npm run production

      #- uses: sitepilot/action-deploy@main
      #  env:
      #    DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      #  with:
      #    args: replace-version ./style.css && rclone sync ./ remote:sites/michascatering/public/wp-content/themes/michascatering --config="./deploy.conf" --exclude-from="./.deployignore"
      #  if: github.ref == 'refs/heads/main'
